[package]
edition = "2021"
name = "jtag_kernel"
version = "0.1.0"
rust-version = "1.75"

[build-dependencies]
cc = "1.0.83"

[dependencies]
bitfield = "0.15.0"
critical-section = { version = "1.1.2", features = ["restore-state-none"] }
tock-registers = "0.9.0"

[features]

# https://github.com/rp-rs/rp2040-project-template/blob/main/Cargo.toml
[profile.dev]
debug = true
debug-assertions = true
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 1
debug = true
opt-level = "s"
